### ISSUE TITLE
bot doesn't get cookie

### ISSUE THREAD

**Issue by fabio1999ita** [thiagown1/amazon-autobuy-bot#1]
![image](https://user-images.githubusercontent.com/27001568/113220461-81252b80-9283-11eb-8fde-e1ebe77ebe46.png)

**Comment by thiagown1** [comment]
Right now this code is specific looking for RTX GPUs, have you setup .env?

This code is a working in progress, I'm implementing now a proxy manager to handle rotation.

**Comment by fabio1999ita** [comment]
yes, i setted user and password and login page, is possible that not work because i try to login in .it domain?

**Comment by thiagown1** [comment]
You can comment #chrome_options.add_argument('--headless') to open the browser. I don't think it's a problem with .it domain. The login page "https://www.amazon.com" is hard coded, It will be easier to find the error in head mode.

If you still have problem after that add me on Discord: Thiago# 0526

**Comment by fabio1999ita** [comment]
> You can comment #chrome_options.add_argument('--headless') to open the browser. I don't think it's a problem with .it domain. The login page "https://www.amazon.com" is hard coded, It will be easier to find the error in head mode.
> 
> If you still have problem after that add me on Discord: Thiago#526

you wrong discord Fabio#6652
